### ISSUE TITLE
Docker file locations

### ISSUE THREAD

**Issue by Helvio88** [DblK/tinshop#32]
Hey there! Great shop, I built a Docker image and it works great!
Unfortunately, I can't really attach to the container because the base image doesn't have a shell.

I brute forced my way to find out that the config file must be placed at / - but I don't know about the titles tb.
Any hints?

Thanks!

**Comment by DblK** [comment]
I will have to dig it, the docker image was a contribution. Since it's only one executable (and a config file) I tend to not use container in this case.

You can also see a `docker-compose` file that indicate the location of the config file.
Concerning the titles db, it should be downloaded automatically at first run.

Is it not working at all?
You should be able to see the log of the container and see if it download or not the titlesdb file.

**Comment by DblK** [comment]
Sure, I thought I put it inside the readme but I did not (but should be in the log).
You should name the file like this :
`[0000000000000000][v0].nsp`
or
`[0000000000000000][v0].nsz`

The most important part is to have the `id` of the game followed by the version (**v** + the number).  
`[gameID][vNumVersion]`

Doing that, it should display the name correctly in `tinfoil`.
Tell me if it fixes the issue.

**Comment by Helvio88** [comment]
Is it not ok to name the file like this?
"Title Name [1234567890][v1].nsp"

**Comment by DblK** [comment]
Yes it should be good. The `gameId` should be 16 characters long.
As long as `gameId` and `version` are there, you can add whatever you want prior or after it.

**Comment by Helvio88** [comment]
Unfortunately that's not working for me. I would love to debug the Docker image to see what's failing when matching names. I don't need anything specific in the config.yaml for that, do I? I'll give you my star, of course! I'm sure we'll get this sorted out in no time 😁

**Comment by Helvio88** [comment]
Just so I understand, if things worked as intended, the `name` would show in tinfoil from the `titledb`?

**Comment by DblK** [comment]
No, the name displayed in `tinfoil` is handled by itself based on the `gameid` and `version` and if not a standard one, by additional `titledb`.

That being said, for `tinfoil` to work, everything needs to be parsed well in `tinshop`.  
Can you change you configuration with debug `noSecurity` to `true` and copy/past the json at the root url of your shop?

With the json output I might be able to understand what's going on 😎

**Comment by Helvio88** [comment]
Can you contact me on Discord? `helvio88`
